import { PHYS } from "./config.js";

// Original fictional vehicles. All dimensions are metres; speeds are m/s.
export const VEHICLES = [
  {
    id: "gt",
    name: "Aster GT",
    kind: "coupe",
    description: "Sport coupe · quick and planted",
    width: 2.16,
    length: 4.64,
    height: 1.48,
    radius: 0.356,
    mass: 1450,
    physics: {},
  },
  {
    id: "hatch",
    name: "Mira Compact",
    kind: "hatch",
    description: "City hatchback · light and nimble",
    width: 1.76,
    length: 3.65,
    height: 1.55,
    radius: 0.31,
    mass: 1050,
    physics: {
      acceleration: 3.8,
      maxSpeed: 34,
      wheelbase: 2.3,
      axles: [-1.12, 1.18],
      halfTrack: 0.77,
    },
  },
  {
    id: "sedan",
    name: "Serein Sedan",
    kind: "sedan",
    description: "Touring sedan · smooth cruising",
    width: 1.9,
    length: 4.7,
    height: 1.52,
    radius: 0.34,
    mass: 1550,
    physics: {
      acceleration: 3.5,
      maxSpeed: 39,
      wheelbase: 2.8,
      axles: [-1.4, 1.4],
      halfTrack: 0.84,
      steerIn: 4,
    },
  },
  {
    id: "suv",
    name: "Terra SUV",
    kind: "suv",
    description: "Tall SUV · steady and relaxed",
    width: 2.04,
    length: 4.5,
    height: 1.95,
    radius: 0.41,
    mass: 1950,
    physics: {
      acceleration: 3.1,
      maxSpeed: 33,
      wheelbase: 2.75,
      axles: [-1.38, 1.37],
      halfTrack: 0.9,
      lateralAcceleration: 6,
      steerIn: 3.7,
    },
  },
  {
    id: "bike",
    name: "Kestrel 400",
    kind: "bike",
    description: "Motorbike · agile, with assisted balance",
    width: 0.9,
    length: 2.25,
    height: 1.95,
    radius: 0.34,
    mass: 280,
    physics: {
      acceleration: 5.2,
      maxSpeed: 40,
      wheelbase: 1.48,
      axles: [-0.74, 0.74],
      halfTrack: 0.06,
      lateralAcceleration: 7,
      steeringAngle: 0.4,
      steeringSpeed: 9,
    },
  },
  {
    id: "truck",
    name: "Atlas Pickup",
    kind: "truck",
    description: "Pickup truck · heavier, with an open cargo bed",
    width: 2.12,
    length: 5.35,
    height: 2.03,
    radius: 0.43,
    mass: 2600,
    physics: {
      acceleration: 2.5,
      maxSpeed: 29,
      brake: 7.5,
      wheelbase: 3.25,
      axles: [-1.62, 1.63],
      halfTrack: 0.94,
      lateralAcceleration: 5.5,
      steerIn: 3.2,
    },
  },
].map((v) => ({
  ...v,
  bounds: { halfWidth: v.width / 2, halfLength: v.length / 2 },
  physics: { ...PHYS, ...v.physics },
}));

export function vehicleSpec(id) {
  return VEHICLES.find((v) => v.id === id) || VEHICLES[0];
}
